//! Counterexamples in the Informal Trace Format.
//!
//! ITF is Apalache's ADR-015 JSON counterexample format, and it is the
//! interface downstream tools already speak: `itf-rs` parses it, the VSCode
//! trace viewer renders it, and `tla-connect` — model-based testing for Rust —
//! collects `*.itf.json` from a checker and replays each trace against a
//! `Driver`. These pin the shape, because a consumer will parse it without
//! asking us anything.

use nixie_core::TermManager;
use nixie_tla_check::bmc::{Bmc, Outcome};
use serde_json::{Value as Json, json};

fn itf(src: &str, depth: u32) -> Json {
    let parsed = nixie_tla_syntax::parse_file(src).expect("parses");
    let loaded = nixie_tla_syntax::LoadedSpec::single(parsed);
    let module = loaded.root_module().expect("has a root module");
    let mut tm = TermManager::new();
    let mut bmc =
        Bmc::prepare(&loaded, module, "Init", "Next", "Inv", &[], &mut tm).expect("prepares");
    assert!(
        matches!(bmc.check(depth, &mut tm), Ok(Outcome::Violation { .. })),
        "expected a violation"
    );
    bmc.counterexample_itf("Spec.tla").expect("an ITF trace")
}

const COUNTER: &str = r"
---- MODULE Counter ----
EXTENDS Integers
VARIABLE x
Init == x = 0
Next == x' = x + 1
Inv  == x < 2
====
";

/// The whole document, shape and content, for the simplest counterexample.
#[test]
fn a_counting_trace_in_full() {
    assert_eq!(
        itf(COUNTER, 4),
        json!({
            "#meta": { "description": "Generated by Nixie", "source": "Spec.tla" },
            "vars": ["x"],
            "states": [
                { "#meta": { "index": 0 }, "x": { "#bigint": "0" } },
                { "#meta": { "index": 1 }, "x": { "#bigint": "1" } },
                { "#meta": { "index": 2 }, "x": { "#bigint": "2" } },
            ]
        })
    );
}

/// An integer is **never** a JSON number. ADR-015 requires the `#bigint` form
/// for every integer, big or small, because JSON parsers impose limits a TLA+
/// integer does not have.
#[test]
fn every_integer_is_a_bigint() {
    let t = itf(COUNTER, 4);
    let states = t["states"].as_array().expect("states");
    for s in states {
        assert!(s["x"]["#bigint"].is_string(), "{s}");
        assert!(!s["x"].is_number(), "{s}");
    }
}

/// A `CONSTANT` is an ITF **param**, not a var, and ADR-015 says it belongs to
/// the initial state — so it is written once, into state 0.
#[test]
fn a_constant_is_a_param_of_the_initial_state() {
    let t = itf(
        r"
---- MODULE WithConst ----
EXTENDS Integers
CONSTANT N
VARIABLE x
Init == x = 0 /\ N = 2
Next == x' = x + 1
Inv  == x # N
====
",
        4,
    );
    assert_eq!(t["params"], json!(["N"]));
    assert_eq!(t["vars"], json!(["x"]));
    let states = t["states"].as_array().expect("states");
    assert_eq!(states[0]["N"], json!({ "#bigint": "2" }));
    for s in &states[1..] {
        assert!(s.get("N").is_none(), "a param repeated in {s}");
        assert!(s.get("x").is_some(), "a var missing from {s}");
    }
}

/// Every value shape ITF defines, in one trace: a set, a record, a tuple and
/// a string.
#[test]
fn the_value_shapes() {
    let t = itf(
        r#"
---- MODULE Shapes ----
EXTENDS Integers
VARIABLES s, r, p, w
Init == /\ s = {1, 2}
        /\ r = [a |-> 1, b |-> TRUE]
        /\ p = <<1, "x">>
        /\ w = "hello"
Next == UNCHANGED <<s, r, p, w>>
Inv  == 3 \in s
====
"#,
        1,
    );
    let st = &t["states"][0];
    assert_eq!(t["vars"], json!(["p", "r", "s", "w"]), "vars are sorted");
    assert_eq!(
        st["s"],
        json!({ "#set": [{ "#bigint": "1" }, { "#bigint": "2" }] })
    );
    assert_eq!(st["r"], json!({ "a": { "#bigint": "1" }, "b": true }));
    assert_eq!(st["w"], json!("hello"));
    // The *shape* of a tuple, not its contents. A component the query never
    // probed comes back defaulted — a defect in the solver's model, written up
    // in `docs/studies/2026-09-14-model-completion-overrides-datatype-fields.md`
    // and pinned by `tests/traces.rs`. This module is responsible for the
    // format; the decoder's values are tested where the decoder is.
    let tup = st["p"]["#tup"].as_array().expect("a #tup");
    assert_eq!(tup.len(), 2);
    assert!(tup[0]["#bigint"].is_string(), "{tup:?}");
    assert!(tup[1].is_string(), "{tup:?}");
}

/// A TLA+ function is an ITF **map**: an array of `[key, value]` pairs,
/// because a key may be any expression where a JSON object key may not.
/// A function on `1..n` is a tuple in TLA+ and comes out as one.
#[test]
fn a_function_is_a_map_and_a_sequence_is_a_tuple() {
    let t = itf(
        r#"
---- MODULE Funs ----
EXTENDS Integers
VARIABLES f, q
Init == f = [i \in {"a", "b"} |-> 1] /\ q = <<7, 8>>
Next == UNCHANGED <<f, q>>
Inv  == q[1] = 8
====
"#,
        1,
    );
    let st = &t["states"][0];
    let q = st["q"]["#tup"].as_array().expect("a #tup");
    assert_eq!(q.len(), 2, "{:?}", st["q"]);
    // A function is a `#map`: an array of `[key, value]` pairs, because a key
    // may be any expression where a JSON object key may not. The keys here are
    // the domain, which is recovered exactly; the values sit behind the
    // array-model gap in
    // `docs/studies/2026-09-14-no-model-for-array-variables.md`, so this pins
    // the encoding and leaves the values to `tests/traces.rs`.
    let m = st["f"]["#map"].as_array().expect("a #map");
    assert_eq!(m.len(), 2, "{:?}", st["f"]);
    let mut keys: Vec<&str> = Vec::new();
    for pair in m {
        let p = pair.as_array().expect("a [key, value] pair");
        assert_eq!(p.len(), 2);
        keys.push(p[0].as_str().expect("a string key"));
        assert!(p[1]["#bigint"].is_string(), "{p:?}");
    }
    keys.sort_unstable();
    assert_eq!(keys, ["a", "b"]);
}

/// Two runs over the same specification produce the same document. A trace
/// that shuffles its own field order is useless to diff and useless to check
/// in.
#[test]
fn the_document_is_deterministic() {
    assert_eq!(
        serde_json::to_string(&itf(COUNTER, 4)).expect("serialises"),
        serde_json::to_string(&itf(COUNTER, 4)).expect("serialises")
    );
}
