//! Gaussian elimination of defining linear equalities for nonlinear goals.
//!
//! Port of the `solve-eqs` half of Z3's QF_NIA preamble
//! (`mk_qfnia_preamble`, `src/tactic/smtlogics/qfnia_tactic.cpp`), the
//! ingredient that makes industrial QF_NIA (VeryMax, AProVE, Dartagnan)
//! tractable: those benchmarks assert hundreds of *defining* equalities
//! (`lam0n0 = -global_invc1_2 + lam0n3`, `lam1n1 = 0`, …) that pin most
//! integer variables to linear combinations of a small core.  Z3's smt core
//! substitutes them during preprocessing (`smt.reduce-asserted`); without
//! this pass OxiZ's nonlinear dispatch feeds all several hundred variables
//! to the arithmetic cores and drowns.
//!
//! # Algorithm
//!
//! 1. Flatten the goal's conjunctive skeleton (nested `and`s) into
//!    individual conjuncts.  Only `and` is descended: a variable under an
//!    `or`/`ite`/quantifier does not have a global defining equality, and
//!    treating one as eliminated would be unsound.  If any quantifier occurs
//!    anywhere in the goal, elimination is skipped entirely (QF goals only).
//! 2. Linearize each equality conjunct `lhs = rhs` over the free module
//!    generated by {variables ∪ canonical monomials ∪ opaque atoms}:
//!    `Σ cᵢ·sᵢ + c₀` with exact integer coefficients.  Products of sums are
//!    distributed only while the expansion stays under a fixed term cap
//!    (`MAX_EXPANDED_TERMS`); `div`/`mod`/`ite`/foreign applications are opaque symbols.
//!    Monomials are keyed by their canonical factor-sorted `TermId`, so
//!    `x*y` and `y*x` unify.
//! 3. Repeatedly pick an equality in which some symbol has coefficient
//!    exactly ±1, solve for that symbol, and substitute it into every other
//!    conjunct at the *term* level (`TermManager::substitute` + `simplify`),
//!    so occurrences inside larger monomials are rewritten too.  Plain
//!    variables are eliminated before monomial symbols (eliminating a
//!    variable shrinks every monomial containing it; the converse can grow).
//! 4. Record `(symbol, defining term)` pairs so a model over the surviving
//!    symbols can be extended back over the eliminated ones (reverse
//!    elimination order) and then concretely verified against the
//!    *original* assertions by the caller.
//!
//! # Soundness
//!
//! Every step is a conjunction-preserving equivalence transformation of the
//! goal, provided the solved equality really is a conjunct and the goal is
//! quantifier-free.  Solving `±s + Σ … = c₀` for `s` and substituting is
//! exact over ℤ.  Coefficients other than ±1 are never solved for (exact
//! integer divisibility of a symbolic right-hand side cannot be decided at
//! this layer); such an equality simply stays in the goal.  A conjunct that
//! simplifies to `false` establishes unsat syntactically; `true` conjuncts
//! are dropped.
//!
//! # Honesty
//!
//! Bounded by conjunct/equation/substitution counts.  Exceeding a bound
//! stops the elimination and returns the goal as far as it was reduced –
//! always an equivalent goal, never a guess.

use num_bigint::BigInt;
use num_traits::{One, Signed, Zero};
use oxiz_core::ast::traversal::{contains_term, get_children};
use oxiz_core::ast::{TermId, TermKind, TermManager};
use std::collections::HashMap;

/// Maximum number of flattened conjuncts considered.
const MAX_CONJUNCTS: usize = 40_000;
/// Maximum number of substitutions performed before stopping at a fixpoint.
const MAX_SUBSTITUTIONS: usize = 40_000;
/// Maximum number of distinct symbols allowed in one linearized equality.
const MAX_SYMBOLS_PER_EQ: usize = 512;
/// Maximum number of terms a product distribution may expand to before the
/// equality is declared un-linearizable (left in the goal untouched).
const MAX_EXPANDED_TERMS: usize = 64;

/// Result of [`gaussian_eliminate`].
pub struct GaussianResult {
    /// The transformed (equivalent) conjunct list.  Empty means the goal was
    /// reduced to `true`; a conjunct equal to `false` means unsat is already
    /// established syntactically.
    pub conjuncts: Vec<TermId>,
    /// `(eliminated symbol, defining term)` in elimination order; replay in
    /// reverse to extend a model of `conjuncts` to the original symbols.
    pub eliminations: Vec<(TermId, TermId)>,
    /// `true` when at least one substitution actually happened.
    pub changed: bool,
}

/// Flatten the conjunctive skeleton and Gaussian-eliminate defining
/// equalities.  See the module docs for the algorithm and soundness
/// argument.
pub fn gaussian_eliminate(assertions: &[TermId], manager: &mut TermManager) -> GaussianResult {
    let mut conjuncts: Vec<TermId> = Vec::new();
    for &a in assertions {
        flatten_and(a, manager, &mut conjuncts);
        if conjuncts.len() > MAX_CONJUNCTS {
            // Honor the budget but keep what we have: the list so far is a
            // prefix-equivalent partition of the goal's conjuncts.
            break;
        }
    }

    let mut eliminations: Vec<(TermId, TermId)> = Vec::new();
    let mut changed = false;

    if contains_quantifier(&conjuncts, manager) {
        return GaussianResult {
            conjuncts,
            eliminations,
            changed: false,
        };
    }

    let mut substitutions = 0usize;
    // Conjuncts whose pivot was rejected (foreign definition, self-reference,
    // degenerate).  A rejected equation is a *constraint of the goal* – it
    // stays in place, merely excluded from future pivot scans.  (Removing it,
    // as an earlier revision did, silently dropped a conjunct and weakened
    // the goal.)
    let mut banned: std::collections::HashSet<TermId> = std::collections::HashSet::new();
    loop {
        if conjuncts.len() > MAX_CONJUNCTS || substitutions >= MAX_SUBSTITUTIONS {
            break;
        }
        let Some((idx, sym, coeff, lin)) = pick_pivot(&conjuncts, &banned, manager) else {
            break;
        };

        // `s = (−c₀ − Σ_{sᵢ≠s} cᵢ·sᵢ) / cₛ` with `cₛ = ±1` – exact over ℤ.
        // Degenerate pivot (e.g. the equation collapses to `s = s`): no
        // information; the conjunct is banned, not dropped.
        let Some(def) = lin.solve_for(&sym, &coeff, manager) else {
            banned.insert(conjuncts[idx]);
            continue;
        };
        // Never eliminate a variable whose definition leaves the polynomial
        // fragment (a purification spur's `select`, an application, …): the
        // substitution would move the foreign leaf into arithmetic atoms and
        // cost the CAD stage its completeness on this goal.
        if definition_is_foreign(def, manager) {
            banned.insert(conjuncts[idx]);
            continue;
        }
        // Acyclicity: the defining term must not mention the variable it
        // defines – directly *or through a monomial* (`(x+1)(y−2)=6` solves
        // to a `y := … x·y …` self-reference; substituting that is not an
        // elimination and can weaken the goal into a spurious sat).
        if contains_term(def, sym, manager) {
            banned.insert(conjuncts[idx]);
            continue;
        }
        eliminations.push((sym, def));
        // The goal was transformed: an equation was consumed and a symbol
        // eliminated, even when no other conjunct mentioned the symbol.
        changed = true;

        let mut subst: rustc_hash::FxHashMap<TermId, TermId> = rustc_hash::FxHashMap::default();
        subst.insert(sym, def);
        let solved = conjuncts.remove(idx);
        banned.remove(&solved);

        let mut next: Vec<TermId> = Vec::with_capacity(conjuncts.len());
        let mut touched = false;
        for &c in &conjuncts {
            if c != solved && contains_term(c, sym, manager) {
                let replaced = manager.substitute(c, &subst);
                let simplified = manager.simplify(replaced);
                banned.remove(&c);
                next.push(simplified);
                touched = true;
            } else {
                next.push(c);
            }
        }
        conjuncts = next;
        substitutions += 1;
        let _ = touched;

        let false_id = manager.mk_false();
        if conjuncts.contains(&false_id) {
            break;
        }
        let true_id = manager.mk_true();
        conjuncts.retain(|&c| c != true_id);
        if conjuncts.is_empty() {
            break;
        }
    }

    GaussianResult {
        conjuncts,
        eliminations,
        changed,
    }
}

/// Pick the (conjunct index, variable, coefficient, linear form) to pivot
/// on: a **plain variable** with coefficient ±1, in the lowest conjunct
/// index for determinism.
///
/// Monomial and opaque symbols are never pivoted.  A variable pivot is a
/// *definition elimination* – `x` is a free variable of the goal, so
/// `G(x) ∧ x = e` ≡ `G(e)` – while "solving" `x·y = 7` for the monomial
/// `x·y` and rewriting the term to `7` is not: it consumes the coupling
/// equation, weakening the goal (sound for Unsat, but it silently destroys
/// unsats exactly where the nonlinear coupling is the point, e.g. a
/// select-product box).  Z3's `solve-eqs` restricts itself the same way.
fn pick_pivot(
    conjuncts: &[TermId],
    banned: &std::collections::HashSet<TermId>,
    manager: &mut TermManager,
) -> Option<(usize, TermId, BigInt, SLin)> {
    for (i, &c) in conjuncts.iter().enumerate() {
        if banned.contains(&c) {
            continue;
        }
        let Some(lin) = linearize_eq(c, manager) else {
            continue;
        };
        if lin.terms.len() > MAX_SYMBOLS_PER_EQ {
            continue;
        }
        for (sym, coeff) in &lin.terms {
            if !coeff.magnitude().is_one() {
                continue;
            }
            let is_var = manager
                .get(*sym)
                .is_some_and(|t| matches!(t.kind, TermKind::Var(_)));
            if is_var {
                return Some((i, *sym, coeff.clone(), lin.clone()));
            }
        }
    }
    None
}

/// `true` when the defining expression of a candidate pivot contains a
/// *foreign numeric* leaf (`select`, uninterpreted application, `store`, …)
/// that the later polynomial stages cannot encode.  Eliminating a
/// purification spur into its `select` moves the select from a skipped
/// interface equality into the arithmetic atoms proper, where it forces the
/// CAD extraction to mark the goal incomplete (and costs the decision).
/// Such a variable stays in the goal; only pure-arithmetic definitions are
/// eliminated (Z3's `solve-eqs` substitutes before purification precisely so
/// the spurs survive).
fn definition_is_foreign(def: TermId, manager: &TermManager) -> bool {
    let mut stack = vec![def];
    let mut seen: std::collections::HashSet<TermId> = std::collections::HashSet::new();
    while let Some(id) = stack.pop() {
        if !seen.insert(id) {
            continue;
        }
        let Some(n) = manager.get(id) else {
            return true;
        };
        match &n.kind {
            TermKind::Var(_) | TermKind::IntConst(_) => {}
            TermKind::Neg(a) | TermKind::Not(a) => stack.push(*a),
            TermKind::Add(xs) | TermKind::Mul(xs) => stack.extend(xs.iter().copied()),
            TermKind::Sub(a, b) => {
                stack.push(*a);
                stack.push(*b);
            }
            // Everything else (selects, applications, div/mod, ite, …) is a
            // foreign or unencodable leaf at this layer.
            _ => return true,
        }
    }
    false
}

/// Extend a model of the reduced goal back over the eliminated symbols.
///
/// Evaluates each defining term under the (progressively extended)
/// environment in reverse elimination order.  Returns `false` if any
/// defining term cannot be evaluated (unknown leaf) – the caller must then
/// treat the model as unverified rather than guess values.
pub fn extend_model(
    eliminations: &[(TermId, TermId)],
    model: &mut HashMap<TermId, BigInt>,
    manager: &TermManager,
) -> bool {
    for (sym, def) in eliminations.iter().rev() {
        if model.contains_key(sym) {
            continue;
        }
        match eval_int(*def, model, manager) {
            Some(v) => {
                model.insert(*sym, v);
            }
            None => return false,
        }
    }
    true
}

/// Evaluate an Int-sorted term under an environment of symbol values.
///
/// Iterative (explicit heap stack) with a memo; supports the exact integer
/// fragment plus `ite`.  Returns `None` for any leaf the environment does
/// not cover, any `let`, and division by zero – callers must treat `None`
/// as "cannot verify", never as a default value.
pub fn eval_int(
    term: TermId,
    env: &HashMap<TermId, BigInt>,
    manager: &TermManager,
) -> Option<BigInt> {
    enum Frame {
        Expand(TermId),
        Combine(TermId),
    }
    let mut stack: Vec<Frame> = vec![Frame::Expand(term)];
    let mut memo: HashMap<TermId, Option<BigInt>> = HashMap::new();
    while let Some(frame) = stack.pop() {
        match frame {
            Frame::Expand(id) => {
                if memo.contains_key(&id) {
                    continue;
                }
                let n = manager.get(id)?;
                match &n.kind {
                    TermKind::IntConst(k) => {
                        memo.insert(id, Some(k.clone()));
                    }
                    TermKind::Var(_) => {
                        let v = env.get(&id).cloned();
                        memo.insert(id, v);
                    }
                    TermKind::Neg(_)
                    | TermKind::Add(_)
                    | TermKind::Sub(_, _)
                    | TermKind::Mul(_)
                    | TermKind::Div(_, _)
                    | TermKind::Mod(_, _) => {
                        // Reserve the memo slot, then evaluate children.
                        memo.insert(id, None);
                        let children = get_children(&n.kind);
                        stack.push(Frame::Combine(id));
                        // Push children in reverse so they are evaluated
                        // left-to-right.
                        for &child in children.iter().rev() {
                            stack.push(Frame::Expand(child));
                        }
                    }
                    // Numeric `ite` needs its *Boolean* condition evaluated,
                    // which this integer evaluator cannot do; an `ite` leaf in
                    // a defining term therefore yields `None` (unverifiable).
                    _ => {
                        memo.insert(id, None);
                    }
                }
            }
            Frame::Combine(id) => {
                let n = manager.get(id)?;
                let children = get_children(&n.kind);
                let mut vals: Vec<Option<BigInt>> = Vec::with_capacity(children.len());
                for &child in children.iter() {
                    vals.push(memo.get(&child).cloned().flatten());
                }
                let result = match &n.kind {
                    TermKind::Neg(_) => vals.into_iter().next()?.map(|v| -v),
                    TermKind::Add(_) => {
                        let mut acc = BigInt::zero();
                        for v in vals {
                            acc += v?;
                        }
                        Some(acc)
                    }
                    TermKind::Sub(_, _) => match vals.as_slice() {
                        [Some(a), Some(b)] => Some(a - b),
                        _ => None,
                    },
                    TermKind::Mul(_) => {
                        let mut acc = BigInt::one();
                        for v in vals {
                            acc *= v?;
                        }
                        Some(acc)
                    }
                    TermKind::Div(_, _) => match vals.as_slice() {
                        [Some(a), Some(b)] if !b.is_zero() => euclidean_div(a, b),
                        // Division by zero is uninterpreted at this layer.
                        _ => None,
                    },
                    TermKind::Mod(_, _) => match vals.as_slice() {
                        [Some(a), Some(b)] if !b.is_zero() => euclidean_mod(a, b),
                        _ => None,
                    },
                    _ => None,
                };
                memo.insert(id, result);
            }
        }
    }
    memo.get(&term).cloned().flatten()
}

/// SMT-LIB Euclidean division: the quotient rounds so the remainder is
/// always non-negative (`r = a − b·(a div b)`, `0 ≤ r < |b|`).
fn euclidean_div(a: &BigInt, b: &BigInt) -> Option<BigInt> {
    // num-bigint `/` and `%` truncate toward zero.  Euclidean division needs
    // a non-negative remainder: when the truncated remainder is negative the
    // quotient shifts by `-sign(b)` and the remainder becomes `r + |b|`.
    let q = a / b;
    let r = a % b;
    if r.is_negative() {
        if b.is_positive() {
            Some(q - 1)
        } else {
            Some(q + 1)
        }
    } else {
        Some(q)
    }
}

fn euclidean_mod(a: &BigInt, b: &BigInt) -> Option<BigInt> {
    let r = a % b;
    if r.is_negative() {
        let abs_b = BigInt::from(b.magnitude().clone());
        Some(r + abs_b)
    } else {
        Some(r)
    }
}

/// A linear form over symbols (variables, canonical monomials, opaque
/// atoms): `Σ cᵢ·sᵢ + c₀`, exact integer coefficients.
#[derive(Clone, Debug)]
struct SLin {
    terms: Vec<(TermId, BigInt)>,
    constant: BigInt,
}

impl SLin {
    fn zero() -> Self {
        Self {
            terms: Vec::new(),
            constant: BigInt::zero(),
        }
    }

    fn is_zero(&self) -> bool {
        self.terms.is_empty() && self.constant.is_zero()
    }

    fn add_scaled(&mut self, other: &SLin, scale: &BigInt) {
        for (s, c) in &other.terms {
            self.add_term(*s, c * scale);
        }
        self.constant += &other.constant * scale;
    }

    fn add_term(&mut self, sym: TermId, coeff: BigInt) {
        if coeff.is_zero() {
            return;
        }
        for (s, c) in &mut self.terms {
            if *s == sym {
                *c += coeff;
                if c.is_zero() {
                    self.terms.retain(|(s2, _)| *s2 != sym);
                }
                return;
            }
        }
        self.terms.push((sym, coeff));
    }

    fn negate(&mut self) {
        for (_, c) in &mut self.terms {
            *c = -c.clone();
        }
        self.constant = -self.constant.clone();
    }

    /// Build the defining term for `sym` given its coefficient `coeff`
    /// (which must be ±1): `sym = (−c₀ − Σ_{sᵢ≠sym} cᵢ·sᵢ) / coeff`.
    fn solve_for(&self, sym: &TermId, coeff: &BigInt, manager: &mut TermManager) -> Option<TermId> {
        let mut rhs_parts: Vec<TermId> = Vec::new();
        if !self.constant.is_zero() {
            rhs_parts.push(manager.mk_int(-self.constant.clone()));
        }
        for (s, c) in &self.terms {
            if s == sym || c.is_zero() {
                continue;
            }
            let mag = c.magnitude();
            let t = if mag.is_one() {
                *s
            } else {
                let coeff_term = manager.mk_int(mag.clone());
                manager.mk_mul([coeff_term, *s])
            };
            rhs_parts.push(if c.is_negative() {
                t
            } else {
                manager.mk_neg(t)
            });
        }
        let mut rhs = match rhs_parts.len() {
            0 => manager.mk_int(0),
            1 => rhs_parts[0],
            _ => manager.mk_add(rhs_parts),
        };
        if coeff.is_negative() {
            rhs = manager.mk_neg(rhs);
        }
        let rhs = manager.simplify(rhs);
        if rhs == *sym {
            return None; // degenerate: `s = s` carries no information
        }
        Some(rhs)
    }
}

/// Linearize an equality conjunct `lhs = rhs` into `lhs − rhs` as an
/// [`SLin`].  Returns `None` for non-equality conjuncts, Boolean
/// equalities, and shapes outside the fragment.
fn linearize_eq(conjunct: TermId, manager: &mut TermManager) -> Option<SLin> {
    let (lhs, rhs) = {
        let n = manager.get(conjunct)?;
        let TermKind::Eq(lhs, rhs) = &n.kind else {
            return None;
        };
        if manager.get(*lhs)?.sort != manager.sorts.int_sort {
            return None;
        }
        (*lhs, *rhs)
    };
    let l = linearize(lhs, manager)?;
    let r = linearize(rhs, manager)?;
    let mut lin = SLin::zero();
    lin.add_scaled(&l, &BigInt::from(1));
    lin.add_scaled(&r, &BigInt::from(-1));
    if lin.terms.len() > MAX_SYMBOLS_PER_EQ {
        return None;
    }
    if lin.is_zero() {
        // `0 = 0` – no information; the caller keeps (and simplifies away)
        // the conjunct itself.
        return None;
    }
    Some(lin)
}

/// Linearize an arithmetic term into an [`SLin`] with an explicit heap
/// stack: nonlinear products become canonical monomial symbols, opaque
/// applications become symbols, and small sum-products are distributed.
fn linearize(term: TermId, manager: &mut TermManager) -> Option<SLin> {
    enum Frame {
        Expand(TermId),
        Combine(TermId),
    }
    let mut stack: Vec<Frame> = vec![Frame::Expand(term)];
    let mut results: Vec<SLin> = Vec::new();
    let mut pending: Vec<(TermId, usize)> = Vec::new();

    while let Some(frame) = stack.pop() {
        match frame {
            Frame::Expand(id) => {
                let n = manager.get(id)?;
                match &n.kind {
                    TermKind::IntConst(k) => results.push(SLin {
                        terms: Vec::new(),
                        constant: k.clone(),
                    }),
                    TermKind::Var(_) => {
                        if n.sort != manager.sorts.int_sort {
                            return None;
                        }
                        results.push(SLin {
                            terms: vec![(id, BigInt::from(1))],
                            constant: BigInt::zero(),
                        });
                    }
                    TermKind::Neg(a) => {
                        pending.push((id, 1));
                        stack.push(Frame::Combine(id));
                        stack.push(Frame::Expand(*a));
                    }
                    TermKind::Add(xs) | TermKind::Mul(xs) => {
                        pending.push((id, xs.len()));
                        stack.push(Frame::Combine(id));
                        for &x in xs.iter().rev() {
                            stack.push(Frame::Expand(x));
                        }
                    }
                    TermKind::Sub(a, b) => {
                        pending.push((id, 2));
                        stack.push(Frame::Combine(id));
                        stack.push(Frame::Expand(*b));
                        stack.push(Frame::Expand(*a));
                    }
                    // `let` bindings may shadow free variables; a conjunct
                    // containing one is left untouched.
                    TermKind::Let { .. } => return None,
                    // Opaque numeric atoms: `div`/`mod` applications (their
                    // defining constraints are asserted separately by the
                    // caller), numeric `ite`, selects, UF applications.
                    _ => {
                        if n.sort != manager.sorts.int_sort {
                            return None;
                        }
                        results.push(SLin {
                            terms: vec![(id, BigInt::from(1))],
                            constant: BigInt::zero(),
                        });
                    }
                }
            }
            Frame::Combine(id) => {
                let (pid, arity) = pending.pop()?;
                if pid != id || results.len() < arity {
                    return None;
                }
                let vals: Vec<SLin> = results.split_off(results.len() - arity);
                let n = manager.get(id)?;
                let out = match &n.kind {
                    TermKind::Neg(_) => {
                        let mut v = vals.into_iter().next()?;
                        v.negate();
                        v
                    }
                    TermKind::Add(_) => {
                        let mut acc = SLin::zero();
                        for v in vals {
                            acc.add_scaled(&v, &BigInt::from(1));
                            if acc.terms.len() > MAX_EXPANDED_TERMS {
                                return None;
                            }
                        }
                        acc
                    }
                    TermKind::Sub(_, _) => {
                        let mut it = vals.into_iter();
                        let mut acc = it.next()?;
                        let b = it.next()?;
                        acc.add_scaled(&b, &BigInt::from(-1));
                        acc
                    }
                    TermKind::Mul(_) => {
                        let mut acc = SLin {
                            terms: Vec::new(),
                            constant: BigInt::from(1),
                        };
                        for v in vals {
                            acc = mul_slins(acc, v, manager)?;
                            if acc.terms.len() > MAX_EXPANDED_TERMS {
                                return None;
                            }
                        }
                        acc
                    }
                    _ => return None,
                };
                results.push(out);
            }
        }
    }
    results.pop()
}

/// Multiply two linear polynomials over {vars ∪ monomial symbols}: products
/// of symbols fold into canonical monomial symbol terms.
fn mul_slins(a: SLin, b: SLin, manager: &mut TermManager) -> Option<SLin> {
    let mut out = SLin::zero();
    out.constant = &a.constant * &b.constant;
    if !a.constant.is_zero() {
        for (s, c) in &b.terms {
            out.add_term(*s, &a.constant * c);
        }
    }
    for (s, c) in &a.terms {
        if !b.constant.is_zero() {
            out.add_term(*s, c * &b.constant);
        }
        for (s2, c2) in &b.terms {
            let mono = canonical_monomial(*s, *s2, manager)?;
            out.add_term(mono, c * c2);
        }
    }
    Some(out)
}

/// Canonical monomial symbol for the product of two symbols: multiply
/// same-symbol powers, sort factors, and rebuild a hash-consed product
/// term.  A `±1` constant factor folds away; other constants cannot be
/// merged here (they never occur: symbols are non-constant by
/// construction).
fn canonical_monomial(a: TermId, b: TermId, manager: &mut TermManager) -> Option<TermId> {
    let mut factors: Vec<TermId> = Vec::new();
    collect_factors(a, manager, &mut factors)?;
    collect_factors(b, manager, &mut factors)?;
    if factors.is_empty() {
        return None;
    }
    // Merge *powers*: `x·x` is the monomial x², not `x`.  Deduplication
    // here collapsed every square onto its base variable, so `x*x = 3`
    // linearized to `x = 3`, the Gaussian preamble consumed it, and the
    // dispatch answered a spurious `sat_empty` on an unsatisfiable goal.
    let mut powers: Vec<(TermId, u32)> = Vec::new();
    for f in factors {
        match powers.iter_mut().find(|(t, _)| *t == f) {
            Some((_, p)) => *p += 1,
            None => powers.push((f, 1)),
        }
    }
    powers.sort_unstable();
    let mut expanded: Vec<TermId> = Vec::new();
    for (t, p) in powers {
        for _ in 0..p {
            expanded.push(t);
        }
    }
    if expanded.len() == 1 {
        return Some(expanded[0]);
    }
    Some(manager.mk_mul(expanded))
}

/// Explode a symbol into its multiplicative factors so products of
/// monomials merge powers.  `Mul` nodes recurse; variables and opaque
/// atoms contribute themselves; `±1` constants fold; anything else cannot
/// be a monomial factor here.
fn collect_factors(sym: TermId, manager: &TermManager, out: &mut Vec<TermId>) -> Option<()> {
    let n = manager.get(sym)?;
    match &n.kind {
        TermKind::Var(_) => {
            out.push(sym);
            Some(())
        }
        TermKind::Mul(xs) => {
            for &x in xs {
                collect_factors(x, manager, out)?;
            }
            Some(())
        }
        TermKind::IntConst(k) if k.magnitude().is_one() => Some(()),
        _ => {
            out.push(sym);
            Some(())
        }
    }
}

/// Flatten `and`-skeleton conjuncts.  Iterative; only descends `And`.
fn flatten_and(term: TermId, manager: &TermManager, out: &mut Vec<TermId>) {
    let mut stack = vec![term];
    while let Some(id) = stack.pop() {
        let Some(n) = manager.get(id) else { continue };
        if let TermKind::And(xs) = &n.kind {
            stack.extend(xs.iter().copied());
        } else {
            out.push(id);
        }
    }
}

/// `true` iff any conjunct contains a quantifier (deeply).
fn contains_quantifier(conjuncts: &[TermId], manager: &TermManager) -> bool {
    let mut seen: std::collections::HashSet<TermId> = std::collections::HashSet::new();
    let mut stack: Vec<TermId> = conjuncts.to_vec();
    while let Some(id) = stack.pop() {
        if !seen.insert(id) {
            continue;
        }
        let Some(n) = manager.get(id) else { continue };
        match &n.kind {
            TermKind::Forall { .. } | TermKind::Exists { .. } => return true,
            _ => {
                let children = get_children(&n.kind);
                stack.extend(children.iter().copied());
            }
        }
    }
    false
}

/// Evaluate an arithmetic term under a *rational* environment (sort-aware:
/// Int-sorted `div`/`mod` use Euclidean semantics, Real-sorted `div` is
/// exact rational division, `select` unfolds `store` towers structurally).
///
/// Boolean-sorted leaves yield `None` (wrong context); an opaque array
/// variable read yields `None` (undecidable).  Iterative (explicit heap
/// stack with memoization), so deep input cannot overflow the native stack.
#[must_use]
pub fn eval_rational(
    term: TermId,
    env: &std::collections::HashMap<TermId, num_rational::BigRational>,
    manager: &TermManager,
) -> Option<num_rational::BigRational> {
    use num_rational::BigRational;
    enum Frame {
        Expand(TermId),
        Combine(TermId),
    }
    let mut stack = vec![Frame::Expand(term)];
    let mut memo: std::collections::HashMap<TermId, Option<BigRational>> =
        std::collections::HashMap::new();
    while let Some(frame) = stack.pop() {
        match frame {
            Frame::Expand(id) => {
                if memo.contains_key(&id) {
                    continue;
                }
                let n = manager.get(id)?;
                let children = get_children(&n.kind);
                match &n.kind {
                    TermKind::True
                    | TermKind::False
                    | TermKind::Not(_)
                    | TermKind::And(_)
                    | TermKind::Or(_)
                    | TermKind::Implies(_, _)
                    | TermKind::Eq(_, _)
                    | TermKind::Le(_, _)
                    | TermKind::Lt(_, _)
                    | TermKind::Ge(_, _)
                    | TermKind::Gt(_, _)
                    | TermKind::Store(_, _, _) => {
                        // Wrong sort for a numeric context, or an array
                        // value this evaluator has no representation for.
                        memo.insert(id, None);
                    }
                    TermKind::IntConst(_) | TermKind::RealConst(_) | TermKind::Var(_) => {
                        let v = match &n.kind {
                            TermKind::IntConst(k) => Some(BigRational::from_integer(k.clone())),
                            TermKind::RealConst(r) => Some(BigRational::new(
                                BigInt::from(*r.numer()),
                                BigInt::from(*r.denom()),
                            )),
                            TermKind::Var(_) => env.get(&id).cloned(),
                            _ => None,
                        };
                        memo.insert(id, v);
                    }
                    TermKind::Select(arr, idx) => {
                        // Structural store-tower unfolding (iterative walk);
                        // each store cell's index/value is evaluated with a
                        // fresh (iterative) call, so native recursion stays
                        // O(1) per select.
                        let mut array_term = *arr;
                        let result = loop {
                            let a_kind = manager.get(array_term).map(|t| t.kind.clone());
                            match a_kind {
                                Some(TermKind::Store(base, k, v)) => {
                                    let kval = eval_rational(k, env, manager)?;
                                    let ival = eval_rational(*idx, env, manager)?;
                                    if kval == ival {
                                        break eval_rational(v, env, manager);
                                    }
                                    array_term = base;
                                }
                                _ => {
                                    // Opaque array variable: only resolvable
                                    // when the read itself is pinned in env.
                                    break env.get(&id).cloned();
                                }
                            }
                        };
                        memo.insert(id, result);
                    }
                    TermKind::Neg(_)
                    | TermKind::Add(_)
                    | TermKind::Sub(_, _)
                    | TermKind::Mul(_)
                    | TermKind::Div(_, _)
                    | TermKind::Mod(_, _)
                    | TermKind::Ite(_, _, _) => {
                        memo.insert(id, None);
                        stack.push(Frame::Combine(id));
                        for &c in children.iter().rev() {
                            stack.push(Frame::Expand(c));
                        }
                    }
                    _ => {
                        memo.insert(id, None);
                    }
                }
            }
            Frame::Combine(id) => {
                if memo.get(&id).is_some_and(|v| v.is_some()) {
                    continue;
                }
                let n = manager.get(id)?;
                let children = get_children(&n.kind);
                let vals: Vec<Option<BigRational>> = children
                    .iter()
                    .map(|&c| memo.get(&c).cloned().flatten())
                    .collect();
                let int_sort = manager.sorts.int_sort;
                let result: Option<BigRational> = match &n.kind {
                    TermKind::Neg(_) => vals.into_iter().next()?.map(|v| -v),
                    TermKind::Add(_) => {
                        let mut acc = BigRational::from_integer(BigInt::from(0));
                        for v in vals {
                            acc += v?;
                        }
                        Some(acc)
                    }
                    TermKind::Sub(_, _) => match vals.as_slice() {
                        [Some(a), Some(b)] => Some(a - b),
                        _ => None,
                    },
                    TermKind::Mul(_) => {
                        let mut acc = BigRational::from_integer(BigInt::from(1));
                        for v in vals {
                            acc *= v?;
                        }
                        Some(acc)
                    }
                    TermKind::Div(_, _) => {
                        let (a, b) = (
                            vals.first().cloned().flatten()?,
                            vals.get(1).cloned().flatten()?,
                        );
                        if b.is_zero() {
                            None // division by zero is uninterpreted
                        } else if n.sort == int_sort {
                            let (ai, bi) = (a.to_integer(), b.to_integer());
                            let (q, r) = (ai.clone() / &bi, ai % &bi);
                            let q = if r.sign() == num_bigint::Sign::Minus {
                                if bi.sign() == num_bigint::Sign::Plus {
                                    q - 1u32
                                } else {
                                    q + 1u32
                                }
                            } else {
                                q
                            };
                            Some(BigRational::from_integer(q))
                        } else {
                            Some(a / b)
                        }
                    }
                    TermKind::Mod(_, _) => {
                        let (a, b) = (
                            vals.first().cloned().flatten()?,
                            vals.get(1).cloned().flatten()?,
                        );
                        if b.is_zero() || n.sort != int_sort {
                            None
                        } else {
                            let (ai, bi) = (a.to_integer(), b.to_integer());
                            let r = ai % &bi;
                            let r = if r.sign() == num_bigint::Sign::Minus {
                                if bi.sign() == num_bigint::Sign::Plus {
                                    r + bi
                                } else {
                                    r - bi
                                }
                            } else {
                                r
                            };
                            Some(BigRational::from_integer(r))
                        }
                    }
                    TermKind::Ite(_, _, _) => {
                        let cv = vals.first().cloned().flatten()?.to_integer();
                        if cv == BigInt::from(1) {
                            vals.get(1).cloned().flatten()
                        } else {
                            vals.get(2).cloned().flatten()
                        }
                    }
                    _ => None,
                };
                memo.insert(id, result);
            }
        }
    }
    memo.get(&term).cloned().flatten()
}

/// Evaluate a Bool-sorted term under a rational environment: the Boolean
/// structure is walked directly, arithmetic leaves delegate to
/// [`eval_rational`].  `None` means "cannot decide" (never `false`).
#[must_use]
pub fn eval_bool_rational(
    term: TermId,
    env: &std::collections::HashMap<TermId, num_rational::BigRational>,
    manager: &TermManager,
) -> Option<bool> {
    use num_rational::BigRational;
    let n = manager.get(term)?;
    match &n.kind {
        TermKind::True => Some(true),
        TermKind::False => Some(false),
        TermKind::Not(a) => Some(!eval_bool_rational(*a, env, manager)?),
        TermKind::And(xs) => {
            let mut all_known = true;
            for &x in xs {
                match eval_bool_rational(x, env, manager) {
                    Some(true) => {}
                    Some(false) => return Some(false),
                    None => all_known = false,
                }
            }
            if all_known { Some(true) } else { None }
        }
        TermKind::Or(xs) => {
            let mut all_known = true;
            for &x in xs {
                match eval_bool_rational(x, env, manager) {
                    Some(true) => return Some(true),
                    Some(false) => {}
                    None => all_known = false,
                }
            }
            if all_known { Some(false) } else { None }
        }
        TermKind::Implies(a, b) => {
            let (a, b) = (
                eval_bool_rational(*a, env, manager)?,
                eval_bool_rational(*b, env, manager)?,
            );
            Some(!a || b)
        }
        TermKind::Eq(a, b) => {
            // Boolean equalities compare recursively; arithmetic ones by
            // rational value.
            if manager
                .get(*a)
                .is_some_and(|t| t.sort == manager.sorts.bool_sort)
            {
                let (x, y) = (
                    eval_bool_rational(*a, env, manager)?,
                    eval_bool_rational(*b, env, manager)?,
                );
                Some(x == y)
            } else {
                let (x, y) = (
                    eval_rational(*a, env, manager)?,
                    eval_rational(*b, env, manager)?,
                );
                Some(x == y)
            }
        }
        TermKind::Le(_, _) | TermKind::Lt(_, _) | TermKind::Ge(_, _) | TermKind::Gt(_, _) => {
            let children = get_children(&n.kind);
            let (a, b) = (
                eval_rational(children[0], env, manager)?,
                eval_rational(children[1], env, manager)?,
            );
            let ord = a.cmp(&b);
            Some(match &n.kind {
                TermKind::Le(_, _) => ord != std::cmp::Ordering::Greater,
                TermKind::Lt(_, _) => ord == std::cmp::Ordering::Less,
                TermKind::Ge(_, _) => ord != std::cmp::Ordering::Less,
                TermKind::Gt(_, _) => ord == std::cmp::Ordering::Greater,
                _ => return None,
            })
        }
        TermKind::Ite(c, t, e) => {
            if eval_bool_rational(*c, env, manager)? {
                eval_bool_rational(*t, env, manager)
            } else {
                eval_bool_rational(*e, env, manager)
            }
        }
        TermKind::Let { .. } => {
            // Bindings key by interned name (`Spur`), which this
            // term-indexed environment cannot resolve; a `let`-bearing
            // assertion is undecidable here (the Gaussian preamble already
            // refuses such goals, so this is defense in depth).
            None
        }
        _ => {
            let _ = BigRational::from_integer(BigInt::from(0));
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn int_env(pairs: &[(TermId, i64)]) -> HashMap<TermId, BigInt> {
        pairs.iter().map(|(t, v)| (*t, BigInt::from(*v))).collect()
    }

    #[test]
    fn euclidean_div_mod_smtlib_semantics() {
        assert_eq!(
            euclidean_div(&BigInt::from(-7), &BigInt::from(2)),
            Some(BigInt::from(-4))
        );
        assert_eq!(
            euclidean_mod(&BigInt::from(-7), &BigInt::from(2)),
            Some(BigInt::from(1))
        );
        assert_eq!(
            euclidean_div(&BigInt::from(7), &BigInt::from(2)),
            Some(BigInt::from(3))
        );
        assert_eq!(
            euclidean_mod(&BigInt::from(-7), &BigInt::from(-2)),
            Some(BigInt::from(1))
        );
        assert_eq!(
            euclidean_div(&BigInt::from(-7), &BigInt::from(-2)),
            Some(BigInt::from(4))
        );
        assert_eq!(
            euclidean_div(&BigInt::from(6), &BigInt::from(3)),
            Some(BigInt::from(2))
        );
    }

    #[test]
    fn eval_int_add_mul_chain() {
        let mut m = TermManager::new();
        let x = m.mk_var("x", m.sorts.int_sort);
        let y = m.mk_var("y", m.sorts.int_sort);
        let xy = m.mk_mul([x, y]);
        let three = m.mk_int(3);
        let e = m.mk_add([xy, three]);
        let env = int_env(&[(x, 4), (y, 5)]);
        assert_eq!(eval_int(e, &env, &m), Some(BigInt::from(23)));
    }

    #[test]
    fn eval_int_rejects_uncovered_leaf() {
        let mut m = TermManager::new();
        let x = m.mk_var("x", m.sorts.int_sort);
        let y = m.mk_var("y", m.sorts.int_sort);
        let e = m.mk_add([x, y]);
        let env = int_env(&[(x, 4)]);
        assert_eq!(eval_int(e, &env, &m), None);
    }

    #[test]
    fn gaussian_eliminates_defining_equality() {
        let mut m = TermManager::new();
        let x = m.mk_var("x", m.sorts.int_sort);
        let y = m.mk_var("y", m.sorts.int_sort);
        // (and (= x (+ y 1)) (>= (* x y) 6))
        let one = m.mk_int(1);
        let y1 = m.mk_add([y, one]);
        let eq = m.mk_eq(x, y1);
        let xy = m.mk_mul([x, y]);
        let six = m.mk_int(6);
        let ge = m.mk_ge(xy, six);
        let goal = m.mk_and([eq, ge]);
        let r = gaussian_eliminate(&[goal], &mut m);
        assert!(r.changed);
        assert_eq!(r.eliminations.len(), 1);
        assert_eq!(r.eliminations[0].0, x);
        // The rewritten product mentions only y.
        let product = r
            .conjuncts
            .iter()
            .find_map(|&c| {
                let n = m.get(c)?;
                let TermKind::Ge(l, _) = &n.kind else {
                    return None;
                };
                m.get(*l)
                    .filter(|ln| matches!(ln.kind, TermKind::Mul(_)))
                    .map(|_| c)
            })
            .expect("rewritten product conjunct");
        assert!(!contains_term(product, x, &m));
    }

    #[test]
    fn extend_model_restores_eliminated_value() {
        let mut m = TermManager::new();
        let x = m.mk_var("x", m.sorts.int_sort);
        let y = m.mk_var("y", m.sorts.int_sort);
        let one = m.mk_int(1);
        let y1 = m.mk_add([y, one]);
        let eq = m.mk_eq(x, y1);
        let xy = m.mk_mul([x, y]);
        let six = m.mk_int(6);
        let ge = m.mk_ge(xy, six);
        let goal = m.mk_and([eq, ge]);
        let r = gaussian_eliminate(&[goal], &mut m);
        let mut model = int_env(&[(y, 5)]);
        assert!(extend_model(&r.eliminations, &mut model, &m));
        assert_eq!(model.get(&x), Some(&BigInt::from(6)));
    }

    #[test]
    fn gaussian_flips_sides_and_neg_coeffs() {
        let mut m = TermManager::new();
        let x = m.mk_var("x", m.sorts.int_sort);
        let y = m.mk_var("y", m.sorts.int_sort);
        // (= (* x (- 1))) i.e.  -x = y  ⟹  x = -y
        let minus_one = m.mk_int(-1);
        let neg_x = m.mk_mul([x, minus_one]);
        let eq = m.mk_eq(neg_x, y);
        let xx = m.mk_mul([x, x]);
        let nine = m.mk_int(9);
        let le = m.mk_le(xx, nine);
        let goal = m.mk_and([eq, le]);
        let r = gaussian_eliminate(&[goal], &mut m);
        assert!(r.changed);
        // Exactly one of {x, y} is eliminated (mk_eq normalizes argument
        // order, so which one the scan reaches first is builder-defined).
        assert_eq!(r.eliminations.len(), 1);
        let eliminated = r.eliminations[0].0;
        assert!(eliminated == x || eliminated == y);
    }

    #[test]
    fn no_gaussian_when_quantified() {
        let mut m = TermManager::new();
        let x = m.mk_var("x", m.sorts.int_sort);
        let y = m.mk_var("y", m.sorts.int_sort);
        let one = m.mk_int(1);
        let y1 = m.mk_add([y, one]);
        let eq = m.mk_eq(x, y1);
        let zero = m.mk_int(0);
        let x0 = m.mk_ge(x, zero);
        let body = m.mk_and([eq, x0]);
        let forall = m.mk_forall([("q", m.sorts.int_sort)], body);
        let r = gaussian_eliminate(&[forall], &mut m);
        assert!(!r.changed);
        assert!(r.eliminations.is_empty());
    }
}
