//! Regression: 194 incremental blocking clauses over an 8-Boolean tautology
//! must stay `sat` (2^8 models exist; each block removes exactly one).
//! Caught as a false `unsat` under certified-mode A/B while landing block-UIP
//! clause shrinking (oxiz-sat): with a real theory attached, the shrunken
//! clause stream eventually derived a clause resolution does not entail.
use oxiz_solver::Context;

#[test]
fn tautology_8bool_194_incremental_blocks_stay_sat() {
    let mut ctx = Context::new();
    let script = r#"(declare-const a Bool)
(declare-const b Bool)
(declare-const c Bool)
(declare-const d Bool)
(declare-const e Bool)
(declare-const f Bool)
(declare-const g Bool)
(declare-const h Bool)
(assert (or a (not a)))
(assert (not (and (= a false) (= b false) (= c false) (= d false) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e false) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e false) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e false) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e false) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e false) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e false) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e false) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e false) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e true) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e true) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e true) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e true) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e true) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e true) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e true) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e true) (= f false) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e true) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e true) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e true) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e true) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e false) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e false) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e false) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e false) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e false) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e false) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e false) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e false) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e true) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e true) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e true) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e true) (= f false) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e true) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e true) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e true) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e true) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e true) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e true) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e true) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e true) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e true) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e true) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e true) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e true) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e true) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e true) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e true) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e true) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e false) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e false) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e false) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e false) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d true) (= e false) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d true) (= e false) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d true) (= e false) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d true) (= e false) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e false) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e false) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e false) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e false) (= f true) (= g false) (= h true))))
(assert (not (and (= a true) (= b false) (= c true) (= d false) (= e false) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c true) (= d false) (= e false) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b true) (= c false) (= d false) (= e false) (= f true) (= g true) (= h true))))
(assert (not (and (= a true) (= b false) (= c false) (= d false) (= e false) (= f true) (= g true) (= h true))))
(assert (not (and (= a false) (= b false) (= c false) (= d false) (= e false) (= f true) (= g true) (= h true))))
(assert (not (and (= a false) (= b true) (= c false) (= d false) (= e false) (= f true) (= g true) (= h true))))
(assert (not (and (= a false) (= b true) (= c false) (= d false) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d false) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d false) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d false) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d true) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d true) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d true) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d true) (= e false) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d true) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d true) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d true) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d true) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d false) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d false) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d false) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d false) (= e true) (= f true) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d false) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d false) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d false) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d false) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d false) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d false) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d false) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d false) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d true) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d true) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d true) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d true) (= e false) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d true) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d true) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d true) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d true) (= e true) (= f false) (= g true) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d true) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d true) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d true) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d true) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d false) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d false) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d false) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d false) (= e true) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d false) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d false) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d false) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d false) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d true) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d true) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d true) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d true) (= e true) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d true) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d true) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d true) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d true) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d true) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d true) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d true) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d true) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d false) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d false) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d false) (= e false) (= f false) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c false) (= d false) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c false) (= d false) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b false) (= c true) (= d false) (= e false) (= f true) (= g false) (= h false))))
(assert (not (and (= a false) (= b true) (= c true) (= d false) (= e false) (= f true) (= g false) (= h false))))
(check-sat)
"#;
    let out = ctx.execute_script(script).expect("script runs");
    let last = out.last().expect("check-sat answered");
    assert!(
        !last.contains("unsat"),
        "194 blocking clauses over a tautology with 256 models must not be unsat (got {last:?})"
    );
}
