//! `pcaltrans` — translate the PlusCal algorithm in TLA+ files.
//!
//! The same command shape as `pcal.trans` (the oracle this translator is
//! checked against): given `.tla` files, rewrite each in place with the
//! translation region updated, keeping a `.old` backup, and writing a
//! `.cfg` sidecar unless `-nocfg`. Or with `-o FILE`, write the translated
//! text elsewhere and leave the input alone.
//!
//! Exit codes follow the reference: 0 translated, non-zero with a
//! diagnostic on stderr otherwise. A construct this subset does not
//! implement is reported as such — never approximated.

use std::io::{Read, Write};

fn main() {
    let mut args: Vec<String> = std::env::args().skip(1).collect();
    let mut nocfg = false;
    let mut out_file: Option<String> = None;
    args.retain(|a| match a.as_str() {
        "-nocfg" => {
            nocfg = true;
            false
        }
        "-help" | "--help" | "-h" => {
            print_help();
            std::process::exit(0);
        }
        _ => true,
    });
    if let Some(i) = args.iter().position(|a| a == "-o") {
        out_file = args.get(i + 1).cloned();
        args.drain(i..=i + 1);
    }
    if args.is_empty() {
        eprintln!("usage: pcaltrans [-nocfg] [-o FILE] SPEC.tla...");
        std::process::exit(2);
    }
    let mut bad = 0;
    for path in &args {
        let mut src = String::new();
        match std::fs::File::open(path).and_then(|mut f| f.read_to_string(&mut src)) {
            Ok(_) => {}
            Err(e) => {
                eprintln!("{path}: {e}");
                bad += 1;
                continue;
            }
        }
        match nixie_tla_syntax::pcal::translate_file(&src) {
            Ok(t) => {
                let dest = out_file.clone().unwrap_or_else(|| path.clone());
                if let Err(e) = write_out(&dest, &t.text, path, &out_file) {
                    eprintln!("{path}: {e}");
                    bad += 1;
                    continue;
                }
                if !nocfg && out_file.is_none() {
                    // The .cfg the reference writes: SPECIFICATION Spec.
                    let cfg = format!("{}.cfg", dest.trim_end_matches(".tla"));
                    if let Err(e) = std::fs::write(
                        &cfg,
                        "SPECIFICATION Spec\n\\* GENERATED BY nixie pcaltrans\n",
                    ) {
                        eprintln!("{cfg}: {e}");
                    }
                }
            }
            Err(e) => {
                eprintln!("{path}: {e}");
                bad += 1;
            }
        }
    }
    std::process::exit(if bad == 0 { 0 } else { 1 });
}

fn write_out(
    dest: &str,
    text: &str,
    src_path: &str,
    out_file: &Option<String>,
) -> std::io::Result<()> {
    if out_file.is_some() {
        let mut f = std::fs::File::create(dest)?;
        f.write_all(text.as_bytes())
    } else {
        // In-place rewrite, like the reference: keep a `.old` backup.
        let backup = format!("{src_path}.old");
        std::fs::copy(src_path, &backup)?;
        let mut f = std::fs::File::create(dest)?;
        f.write_all(text.as_bytes())
    }
}

fn print_help() {
    println!("pcaltrans — translate the PlusCal algorithm in a TLA+ file");
    println!();
    println!("usage: pcaltrans [-nocfg] [-o FILE] SPEC.tla...");
    println!();
    println!("  -o FILE    write the translated text to FILE, leaving the input");
    println!("             untouched (no .old backup, no .cfg)");
    println!("  -nocfg     do not write the .cfg sidecar");
    println!();
    println!("Without -o, the input is rewritten in place with a .old backup,");
    println!("matching pcal.trans. The translation region is placed between");
    println!("\\* BEGIN TRANSLATION and \\* END TRANSLATION markers.");
}
